version: '3.9'

services:
  nextapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TMDB_READ_TOKEN: ${TMDB_READ_TOKEN}
        TMDB_API_KEY: ${TMDB_API_KEY}
        SUPABASE_URL: ${SUPABASE_URL}
        SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
        SUPABASE_SERVICE_ROLE_SECRET: ${SUPABASE_SERVICE_ROLE_SECRET}
    env_file:
      - .env.production
    restart: always
    expose:
      - "3005"

  nginx:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/streaming.eggspank.cloud/fullchain.pem:/etc/ssl/certs/nginx.crt:ro
      - /etc/letsencrypt/live/streaming.eggspank.cloud/privkey.pem:/etc/ssl/private/nginx.key:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nextapp
    restart: always

