version: '3.8'

services:
  nextjs:
    build: .
    container_name: streaming-web
    restart: always
    expose:
      - 3005

  nginx:
      image: nginx:alpine
      container_name: nginx-proxy
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro